LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "You can only bet once"), "Solo puedes apostar una vez");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "I have sent you bet list"), "Te he enviado un listado de apuestas");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "Failed to send bet list, do you have your dms off?"), "Error al enviar listado de apuestas, ¿tienes habilitados los DMs?");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "Pick where you want to place your chip. Type cancel to cancel. (You have 10 seconds to pick where you want to place it)"), "Elige donde colocar tu chip. Escribe Cancelar para cancelar. (Tienes 10 segundos para elegir donde ponerlo)");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "You did not pick where you want to place your chip on time."), "No elegiste donde colocar tu chip a tiempo.");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "Bet is incorrect. Please cancel your bet and do <RCommand>bets to check what bets you can and cannot do"), "La apuesta es  incorrecta. Por favor cancela y escribe <RCommand>para ver que apuestas puedes o no hacer");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "You have canceled your bet"), "Has cancelado tu apuesta");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "Joining Game"), "Unirse al juego");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "Starting game in <Seconds> seconds"), "El juego inicia en <Seconds> segundos");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "Spinning..."), "Girando...");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "Rolled Black <Number>"), "Tiraste <Number> Negro");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "Rolled Red <Number>"), "Tiraste <Number> Rojo");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "Roulette Wins"), "La Ruleta Gana");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "The minium withdrawal is <Amount>"), "El minimo a retirar es  <Amount>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "You do not have enough to withdrawal <Bal>, You only have <Bank>"), "No tienes suficiente para retirar <Bal>, Solo tienes <Bank>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "**Money Withdrawn**\n\nYou just withdrawn <Bal> from your bank\n\nYou now have <Bal> in your wallet and <Bank> in your bank"), "**Dinero retirado**\n\nSolo retiraste <Bal> de tu banco\n\nAhora tienes <Bal> en tu billetera y <Bank> en tu banco");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "You can use their Username, Display Name, Or tag"), "Puedes utilizar sus nombres de usuario, sobrenombre, O taggearlos");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "<User> chewed on <User>!"), "<User> mordió a <User>!");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "<User> started turning red?"), "<User> se está sonrojando?");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "<User> started crying ;("), "<User> comenzó a llorar ;(");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "<User> started cuddling with <User>! (≧ヘ≦)"), "<User> se está acurrucando con <User>! (≧ヘ≦)");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "<User> started dancing!"), "<User> comenzó a bailar!");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "<User> hugged <User>!"), "<User> abrazó a <User>!");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "<User> kissed <User>!"), "<User> besó a <User>!");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "<User> licked <User>!"), "<User> lamió a <User>!");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "<User> started patting <User>"), "<User> comenzó a acariciar a <User>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "<User> poked <User>!"), "<User> pinchó a <User>!");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "<User> punched <User>! :("), "<User> golpeó a <User>! :(");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "<User> slapped <User>!"), "<User> cacheteó a <User>!");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "<User> is getting tired."), "<User> se está cansando.");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "<User> has a smug look on their face >:)"), "<User> tiene una mirada petulante >:)");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "<User> is staring at <User>!"), "<User> está mirando fijamente a <User>!");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "<User> started tickling <User>!"), "<User> le está haciendo cosquillas a <User>!");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "Image provided by <Provider>"), "Imagen proporcionada por <Provider>");
