LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Bets"), "Apuestas");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "You need to ask Rem a question for a prediction"), "Necesitas hacerle una pregunta a Rem para obtener una predicción");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "You need the `Manage Messages` permission on this channel to use this command"), "Necesita tener el permiso `Administrar mensajes 'en este canal para usar este comando");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Please give me a message to repeat"), "Por favor dame un mensaje para repetir");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Weapons"), "Armas");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Crates"), "Cajas");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Food"), "Alimento");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "<Weapon> Owned: <Amount> Uses: <Uses>"), "<Weapon> Municiones: <Amount> Usos: <Uses>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "<Type> Owned: <Amount>"), "<Type> Municiones:: <Amount>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "This weapon is a gun, not a knife"), "Esta arma es una pistola, no un cuchillo");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Common"), "Común");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Uncommon"), "Poco común");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanishh", "Rare"), "Raro");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Legendary"), "Legendario");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Mythic"), "Mitico");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Gun"), "Pistola");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Knife"), "Cuchillo");
