LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Please give me a valid amount"), "Por favor asigna un importe valido");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Amount must be a number"), "El importe debe ser un número");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Amount must be more than 0"), "El importe debe ser mayor a 0");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "You do not have enough to place a <Amount> bounty, You only have <Bal>"), "No tienes suficiente para dar <Amount> en recompensa, solo tienes <Bal>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Failed to parse bounty"), "Error al calcular la recompensa");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "You added <Amount> to <User>'s Bounty"), "Le diste <Amount> de recompensa a <User>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "<Server> Top Bounties"), "<Server> Top Recompensas");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "There are no bounties in  <Server>"), "No hay recompensas en <Server>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "You claimed your gift for voting and received an <Crate> Crate"), "Reclamaste tu recompensa por votar y recibiste una caja <Crate>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "You claimed your gift for voting and received a <Crate> Crate"), "Reclamaste tu recompensa por votar y recibiste una caja <Crate>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "You have claimed your voting gift"), "Reclamaste tu recompensa por votar");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "You claimed your gift for voting and received an <Prize>"), "Reclamaste tu recompensa por votar y recibiste una <Prize>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "You claimed your gift for voting and received a <Prize>"), "Reclamaste tu recompensa por votar y recibiste un <Prize>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "You bought a winning lottery ticket and won <Amount>"), "Compraste un billete de lotería ganador y ganaste <Amount>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "You found a wallet on the ground that contained <Amount>"), " Encontraste una billetera en el piso y tenía <Amount>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "You worked at the grocery store and earned <Amount>"), "Trabajaste en la tienda de abarrotes y ganaste <Amount>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "You streamed your \"amazing\" content on Twitch and made <Amount>"), "Transmitió su contenido \"increíble\" en Twitch y ganó <Amount>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "You went to work as a plumber and earned <Amount>"), "Trabajaste como fontanero y ganaste <Amount>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "On your way to work you got in a car accident and had to pay <Amount> for the damages"), "De camino al trabajo tuviste un accidente y debiste pagar <Amount> por los daños");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "You went to your local grocery store and stole <Amount> from the cash register"), "Fuiste a la tienda de conveniencia y robaste <Amount> de la caja registradora");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "You found a homeless man on the street. You took all of his possessions and sold it for <Amount>>"), "Encontraste un vagabundo en la calle. Tomaste todas sus posesiones y las vendiste por <Amount>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "You went to church and stole <Amount> from the donation basket"), "Fuiste a la iglesia y robaste <Amount> del diesmo");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "You found a homeless man on the street. When you attempted to rob him he pulled out his badge and fined you <Amount>"), "Encontraste un vagabundo en la calle. Cuando intentaste robarle, sacó su placa y te multó por <Amount>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "You attempted to rob an old lady, but she robbed you instead for <Amount>"), "Intentaste robarle a una anciana, pero ella te robó a tí <Amount>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "You went to your local grocery store attempted to rob it, You were caught by the security guard and fined <Amount>"), "Fuiste al supermercado e intentaste robarlo.Te atrapó  el guardia de seguridad y fuiste multado por <Monto>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "The minium desposit is <Amount>"), "El mínimo a depositar es <Amount>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "You do not have enough to deposit <Amount>, You only have <Bal>"), "No tienes suficiente para depositar <Amount>, solo tienes <Bal>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "**Money Desposited**\n\nYou just deposited <Bal> in your bank\n\nYou now have <Bal> in your wallet and <Bank> in your bank"), "**Money Desposited**\n\nAcabas de depositar <Bal> en tu banco\n\nAhora tienes <Bal> en la billetera y  <Bank> en tu cuenta");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "<Server>'s Leaderboards"), "Tabla de clasificaciones del <Server>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "There are no leaderboards in <Server>"), "No existe tabla de clasificaciones en el <Server>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "**You Won**\n\nYou rolled a <Number> and won <Bal>"), "**Ganaste**\n\nTiraste un <Number> y ganaste <Bal>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "**You Lost**\n\nYou rolled a <Number> and lost <Bal>"), "**Perdiste**\n\nTiraste un <Number> y perdiste <Bal>");
