LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Rem Info"), "Rem Info");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Discord Server"), "Servidor de Discord ");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Lead Dev"), "Desarrollador Principal");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Version"), "Version");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Servers"), "Servidores");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Memory Usage"), "Uso de Memoria");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Website"), "Sitio Web");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Made With"), "Hecho con");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Discord.Net"), "Discord.Net");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "<Day> days, <Hour> hours, <Minute> minutes, <Second> seconds"), "<Day> día, <Hour> hora, <Minute> minuto, <Second> segundo");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Uptime"), "Tiempo Activo");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Shard <Shard>"), "Casco <Shard>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Open Database Connections: <Connections>"), "Abrir Base de Datos: <Connections>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "**API Latency** <APILatency>ms\n**Bot Latency** <BotLatency>ms"), "**API en estado latente ** <APILatency>ms\n**Bot en estado latente** <BotLatency>ms");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Ping Result"), "Resultado del Ping");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "You have successfully sent your report to the admins"), "Has enviado exitosamente tu reporte a los administradores");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Thank you for your suggestion!"), "¡Muchas gracias por la sugerencia!");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Cash"), "Efectivo");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Bank"), "Banco");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Net Worth"), "Patromonio Neto");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "BLACKJACK"), "BLACKJACK");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Your Cards"), "Tus Cartas");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Dealers Cards"), "Cartas del Repartidor");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "BUST"), "FRACASASTE");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "WIN"), "GANASTE");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "PUSH"), "GANANCIA");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "LOSS"), "PERDIDA");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Value: <Value>"), "Valor: <Value>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Level"), "Nivel");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "XP"), "XP");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Health"), "Salud");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Bounty"), "Recompensa");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Winners"), "Ganadores");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Losers"), "Perdedores");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Romaji Title"), "Titulo en Romaji");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Status"), "Estado");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Episodes"), "Episodios");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Unkown"), "Desconocido");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Air Date"), "Fecha fijada");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Average Score"), "Puntuacion Media");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Genres"), "Generos");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "null"), "nulo");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Trailer"), "avance");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "This anime/manga is for adults. If you want to view it you need to be in an nsfw channel"), "Este anime/manga es para adultos. Si lo quieres ver debes ir a un canal nsfw");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Cannot find anime with title <Anime>"), "No puedo encontrar un anime con el título  <Anime>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "<Users>'s Avatar!"), "Este es el avatar de <Users>!");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Invalid Args"), "Argumentos invalidos");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Please give valid letters to send"), "Por favor da una carta valida para entregar");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Content is to long, Message needs to be under 2000 characters."), "En contenido es demasiado largo, el mensaje necesita tener menos de  2000 caracteres.");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "It is certain"), "Es cierto");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "It is decidedly so"), "Es decididamente así");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Without a doubt"), "Sin dudas");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Yes definitely"), "Si, definitivamente");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "You may rely on it"), "Puedes confiar en ello");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "As I see it yes"), "Como yo lo veo, si.");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Most likely"), "Es muy probable");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Outlook good"), "Buena perspectiva");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Yes"), "Si");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Signs point to yes"), "Todo indica que si");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Reply hazy try again"), "Estoy confundida, intenta otra vez");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Ask again later"), "Pregunta nuevamente mas tarde");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Better not tell you now"), "Mejor no decirtelo ahora");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Cannot predict now"), "No lo puedo predecir ahora");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Concentrate and ask again"), "Concentrate y  pregunta nuevamente");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Don't count on it"), "No cuentes con ello");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "My reply is no"), "Mi respuesta es no.");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "My sources say no"), "Mis fuentes dicen que no");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Outlook not so good"), "No tienes buenas perspectivas");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Very doubtful"), "Demasiado dudoso");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Question <Question>"), "Pregunta <Question>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Answer <Answer>"), "Respuesta <Answer>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Coinflip"), "Tirar la moneda");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "The coin landed on Heads"), "La moneda cayó en cara");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "The coin landed on Tails"), "La moneda cayó en ceca");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Cannot find anime with genre <Genre> and year <Year>"), "No logro encontrar un anime con genero <Genre> del año <Year>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Cannot find anime with year <Year>"), "no encuentro anime del año <Year>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Cannot find anime with genre <Genre>"), "no encuentro anime del genero <Genre>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Genre/Year is empty"), "Genero/año estan vacios");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Anime is empty"), "El anime esta vacío");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "I do not have permission to delete messages"), "No tengo permiso de borrar mensajes");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Common Crate"), "Caja Comun");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Uncommon Crate"), "Caja poco comun");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Rare Crate"), "Caja Rara");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Legendary Crate"), "Caja Legendaria");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Mythic Crate"), "Caja Mistica");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "**Common Winnings**"), "**Ganancias Comunes**");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "**Uncommon Winnings**"), "**Ganancias poco comunes**");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "**Rare Winnings**"), "**Ganancias extrañas**");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "**Legendary Winnings**"), "**Ganancias Legendarias**");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "**Mythic Winnings**"), "**Ganancias Misticas**");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Price"), "Precio");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Common Odds"), "Probabilidades Comunes");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Uncommon Odds"), "Probabilidades Poco Comunes");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Rare odds"), "Probabilidades Raras");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Legendary Odds"), "Probabilidades Legandarias");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Mythic Odds"), "Probabilidades Misticas");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Type"), "Tipo");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Rarity"), "Rareza");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Uses"), "Usos");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Damage"), "Daño");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Can Open"), "puedo abrir");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Kills"), "Matar");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Deaths"), "Muertes");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "K/D Ratio"), "Relacion K/D");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Damage Done"), "Daño hecho");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Won From Gambling"), "Ganado en Apuestas");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Lost From Gambling"), "Perdido en Apuestas");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Failed to get stats"), "Error al obtener estado");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Statistic must be an Item, Crate, or a User"), "El tipo debe ser un artículo, una caja o un usuario");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "You can only use nsfw commands in nsfw channels"), "Solo puedes utilizar comandos nsfw en canales nsfw");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Lewd Neko"), "Neko Lascivo");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Rem Lewd"), "Rem Lasciva");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Thicc Thighs"), "Lindo cuerpo");
