LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "Number is too big!"), "¡El número es demasiado grande!");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "Amount is too large"), "La cantidad es demasiado grande");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "Please give me a valid crate"), "Por favor pide una caja valida");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "Amount cannot be less than 1"), "La cantidad no puede ser menos de 1");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "<Crate> crate does not exist"), "La <Crate> caja no existe");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "Current crates: Mythic, Legendary, Rare, Uncommon, Common"), "Cajas actuales: mítica, legendaria, rara, poco común, común");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "<Crate> is not for sale"), "La <Crate> no esta a la venta");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "You do not have enough money to buy <Amount> <Crate> crates\n\nYou need <NeededAmount>"), "No tienes suficiente dinero <Amount> para comprar estas <Crate> caja\n\nNecesitas <NeededAmount>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "You do not have enough money to buy <Amount> <Crate> crate\n\nYou need <NeededAmount>"), "No tienes suficiente dinero <Amount> para comprar esta <Crate> caja\n\nNecesitas <NeededAmount>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "You cannot have more than 999,999,999 crates"), "No puedes tener mas de 999,999,999 cajas");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "You just bought <Amount> <Crate> crates"), "Acabas de comprar varias cajas <Crate> por <Amount>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "You just bought <Amount> <Crate> crate"), "Acabas de comprar una caja <Crate> por <Amount>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "Please give me a valid Amount/Item"), "Por favor dame  Cantidad/Item validos");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "You can't donate to yourself"), "No puedes hacer donaciones a ti mismo");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "Failed to parse string"), "Error al analizar la cadena");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "You do not have enough money to donate <Amount> You only have <Bal>"), "No tienes suficiente dinero para donar <Amount> solo tienes <Bal>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "You have successfully given <User> <Amount>"), "Le has dado a <User> la suma de <Amount> con exito ");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "Give me a valid food name"), "Proporciona un nombre valido de comida  ");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "You are already at the max health <MaxHealth>"), "Ya estas a la salud máxima <MaxHealth>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "You just ate an <Food> and you are now at <Health>"), "Acabas de comer unos <Food> y ahora tienes <Health>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "You just ate a <Food> and you are now at <Health>"), "Acabas de comer un <Food> y ahora tienes <Health>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "You have <Owned> <Food> left"), "Te quedan <Owned> <Food> ");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "You just went fishing and came back with a <Food>"), "Fuiste a pescar y volviste con un <Food>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "You just went fishing and came back with an <Food>"), "Fuiste a pescar y volviste con unos <Food>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "You just caught a <Food> in the wilderness"), "You just caught a <Food> in the wilderness");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "You just caught an <Food> in the wilderness"), "Acabas de atrapar un <Food> en el desierto");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "You do not have anything in your inventory"), "No hay nada en tu inventario");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "They do not have anything in their inventory"), "No tienen nada en sus inventarios");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "You can only open 10 crates at a time"), "Solo puedes abrir 10 cajas a la vez");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "You do not own any <Crate> crates"), "No tienes ninguna <Crate> caja");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "You do not have enough crates to open <Amount>, you only have <Owned>"), "No tienes suficientes cajas para abrir <Amount>, solo tienes <Owned>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "Please give me a valid weapon"), "Por favor proporciona un arma valida");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "You cannot shoot yourself"), "No te puedes disparar a tí mismo");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "<Weapon> does not exist"), "<Weapon> no existe");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "You do not own any <Weapon>'s"), "No tienes ningun <Weapon>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "This weapon is a knife, Not a gun"), "El arma es un cuchillo, no un revolver");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "To use this weapon appropriately use <Shoot>"), "Para usar esta arma apropiadamente escribe <Shoot>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "Health Before"), "Salud antes");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "Health After"), "Salud después");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "Money Lost"), "Dinero perdido");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "You cannot have more than the max bal in your wallet"), "No puedes tener más que el máximo balance en tu billetera");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "The weapon has reached max uses and has been destroyed"), "El arma alcanzó su maximo de usos y ha sido destruida ");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "You have been killed"), "Te han asesinado");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "User that killed you"), "El usuario que te asesinó");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "<User> Just took 50% of your money <MoneyTaken>"), "<User> acaba de tomar el 50% de tu dinero <MoneyTaken>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "<User> had a bounty of <Bounty> and it has been collected by <User>"), "<User> tenía una recompensa de <Bounty> y ha sido reclamada por <User>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "<User> Just shot <User> with a <Weapon>"), "<User> le disparó a <User> con un <Weapon>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "<User> Just shot <User> with a <Weapon> and died"), "<User> le disparó a  <User>  con un <Weapon> y murió");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "<User> Just shot <User> with an <Weapon>"), "<User> le disparó a <User> con unas <Weapon>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "<User> Just shot <User> with an <Weapon> and died"), "<User> le disparó a  <User> con unas <Weapon> y murió");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "You used this weapon more than it's intended use! This weapon has been deleted from your inventory"), "¡Usaste esta arma más de lo previsto! Esta arma ha sido eliminada de tu inventario");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "You cannot stab yourself"), "No puedes apuñalarte");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "<User> Just stabbed <User> with a <Weapon>"), "<User> apuñaló a <User> con un <Weapon>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "<User> Just stabbed <User> with a <Weapon> and died"), "<User> apuñaló a  <User> con un <Weapon> y murió");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "<User> Just stabbed <User> with an <Weapon>"), "<User> apuñaló a <User> con unas <Weapon>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "<User> Just stabbed <User> with an <Weapon> and died"), "<User> apuñaló a  <User> con unas <Weapon> y murió");
