LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "You need the `Administrator` permission to use this command"), "Necesitas permiso del `Administrador` para usar este comando");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "Currency cannot be empty"), "La petición no puede estar vacía");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "Currency is too large, It must be under 30 characters"), "la petición es muy larga, debe tener menos de 30 caracteres");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "Emote not parsed, Emote must be in the current server and needs to be custom."), "Emote no agregado, el Emote debe agregarse al servidor y ser personalizado.");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "You cannot use default discord emojis!"), "¡no puedes utilizar los emotes predeterminados de Discord!");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "Currency changed to <Currency>"), "Petición cambió a <Currency>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "<Option> has been reset"), "<Option> fue reiniciada");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "Please be consistent with the user you're choosing"), "Por favor se coherente con el usuario que eligiras");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "Failed to get user"), "Error al obtener el usuario");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "If you are attempting to reset the server please do not give any arguments. If you are trying to reset a user give me a valid user"), "Si está intentando restablecer el servidor, no dé ningún argumento. Si está intentando restablecer un usuario, deme un usuario válido");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "You are attempting to reset <Server>, This will reset every person in this guild, Please use this command again to continue. Command will expire in 10 seconds"), "Estás intentando restablecer <Servidor>. Esto restablecerá a todas las personas de esta organización. Utiliza este comando nuevamente para continuar. El comando expirará en 10 segundos");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "You are attempting to reset <User>, This will only reset <User> and no one else, Please use this command again to continue. Command will expire in 10 seconds"),"Está intentando restablecer <Usuario>, esto solo restablecerá <Usuario> y nadie más.Utilice este comando nuevamente para continuar.El comando expirará en 10 segundos.");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "Prefix cannot be empty"), "Prefijo no puede estar vacio");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "Prefix cannot be more than 8 characters"), "Prefijo no puede contener mas de 8 caracteres");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "You cannot change the prefix to <Prefix> the prefix is already <Prefix>"), "No puedes cambiar el prefijo a <Prefix> el prefijo ya es <Prefix>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "Prefix has been changed to <Prefix>"), "Prefijo ha sido actualizado a <Prefix>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "You do not have permission to use this command"), "No tienes permiso de utilizar este comando");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "You need the Manage Guild permission to use this command"), "Necesitas permisos de manager para usar este comando");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "You must be a Legendary Supporter or higher on our Patreon"), "Necesitas ser Soporte Legendario o poseer un rol mas alto en nuestro Patreon");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "Please give me a valid Reason"), "Por favor dame una razón valida");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "Please give me a valid user (User cannot be a bot)"), "Por favor asigna un usuario valido (Usuario no puede ser un bot)");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "Failed to parse balance"), "Error al mostrar balance");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "You can not add more than <Bal>"), "No puedes sumar más de <Bal>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "<User> just gave <Bal> to <User>"), "<User> acaba de darle <Bal> a <User>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "<User> just gave <Bal> to <User> for <Reason>"), "<User> acaba de darle <Bal> a <User> por <Reason>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "Amount must be a number or equal 'all'"), "Cantidad debe ser un número o 'todo'");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "The minium gamble is <Amount>"), "La apuesta minima es  <Amount>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "You do not have enough to gamble <Bal>, You only have <Bal>"), "No tienes suficiente <Bal> para apostar, solo tienes <Bal>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "You Won You rolled a <Number> and won <Bal>"), "¡Ganaste! tiraste un <Number> y tu premio es <Bal>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "You Lost You rolled a <Number> and lost <Bal>"), "¡Perdiste! tiraste un <Number> y perdiste <Bal>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "Couldn't find user, If this problem countinues ping them"), "No encuentro usuario, si el problema persiste ping ");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "There is a timeout on this command"), "Existe un tiempo fuera para este comando");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "You can use this command in <Timeout>"), "Puedes usar este comando en <Timeout>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "Failed to parse bal/bank"), "Error al calcular bal/bank");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "Type hit to draw another card, or stand/stay to stand."), "Escribe hit para robar otra carta, o detener/parar para detenerte.");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "If you do not pick a choice in <Time> seconds it will stand for you"), "Si no eliges una opcion en <Time> segundos se detrandrá por ti");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "You did not lose any money."), "No perdiste dinero.");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "Money won <Amount>"), "Dinero ganado <Amount>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Español", "Money lost <Amount>"), "Dinero perdido <Amount>");
