LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "You did not reply in time"), "No contestaste a tiempo");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "<Language> is not a valid language"), "<Language> no es un idioma valido");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "The servers language is already set to <Language>"), "El idioma del servidor ya está configurado en <Language>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Language has been changed to <Language>"), "El idioma ha sido cambiado a  <Language>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Please pick the desired language"), "Por favor elige un idioma");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "You have 30 seconds to reply"), "Tienes 30 segundos para responder");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "You have not voted"), "No haz votado");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "If you have voted in the last 12 hours please wait a few minutes and try again. Click this link to vote <Link>"), "Si votaste en las ultimas 12 horas por favor espera unos minutos e intenta nuevamente. Haz click en este link para votar <Link>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "You have claimed your voting gift"), "Reclamaste tu regalo por votar al bot");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "You claimed your gift for voting and received an <Item>"), "Reclamaste tu regalo por votar al bot y recibiste <Item>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "You claimed your gift for voting and received a <Item>"), "Reclamaste tu regalo por votar al bot y recibiste <Item>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "You claimed your gift for voting and received <Money>, The money you win has been increased due to your <Votes> votes"), "Reclamaste tu regalo por votar al bot y recibiste <Money>, El dinero que ganaste aumentó debido a tus <Votes> votos");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "You claimed your gift for voting and received <Money>"), "Reclamaste tu regalo por votar al bot y recibiste <Money>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "You claimed your gift for voting and received an <Crate> Crate, Your odds have been increased due to your <Votes> votes"), "Reclamaste tu regalo por votar al bot y recibiste una <Crate> Caja, Sus probabilidades han aumentado debido a tus <Votes> votos");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "You claimed your gift for voting and received a <Crate> Crate, Your odds have been increased due to your <Votes> votes"), "Reclamaste tu regalo por votar al bot y recibiste una <Crate> Caja, Sus probabilidades han aumentado debido a tus <Votes> votos");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "You claimed your gift for voting and received an <Crate> Crate"), "Reclamaste tu regalo por votar al bot y recibiste una <Crate> Caja");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "You claimed your gift for voting and received a <Crate> Crate"), "Reclamaste tu regalo por votar al bot y recibiste una <Crate> Caja");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "You do not have any extra gifts to claim"), "No tienes ningun regalo extra por reclamar");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", ":x: Be in the support server\n:x: Nitro boost the support server\n:x: Be a patreon supporter"), ":x: Unete al server soporte\n:x: Nitro mejora el servidor de soporte\n:x: Apoyanos en Patreon");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "You claimed your gift for being a <Role> and recieved"), "Reclamó y recibió su regalo por ser un <Role>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Claims"), "Reclamos");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "I have sent the command list to your direct messages"), "Te envié un listo de comandos por mensaje directo");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Failed to send direct message. Check privacy settings and try again"), "Error al enviar mensaje directo. Chequea tus ajuste de privacidad e intenta nuevamente");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Command does not exist!"), "¡Ese comando no existe!");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Aliases"), "Alias");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Summary"), "Resumen");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Suggestion cannot be empty"), "Laa sugerencia no puede estar vacía");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Spanish", "Report cannot be empty"), "El reporte no puede estar vacío");
